<?php
return new \Phalcon\Config([
    'acl' => [
        'department'=>[
            'title'=>'公司组织',
            'actions'=>[
                'department'=>[
                    [
                        'action'=>'index',
                        'title'=>'组织架构'
                    ],
                    [
                        'action'=>'save',
                        'title'=>'新增编辑组织架构',
                    ],
                    [
                        'action'=>'delete',
                        'title'=>'删除组织架构',
                    ]
                ],
                'rank'=>[
                    [
                        'action'=>'index',
                        'title'=>'职级职等',
                    ]
                ],
                'worker'=>[
                    [
                        'action'=>'index',
                        'title'=>'员工列表'
                    ],
                    [
                        'action'=>'edit',
                        'title'=>'编辑员工列表',
                    ]
                ]
            ],
        ],
        'customer'=>[
            'title'=>'客户',
            'actions'=>[
                'customer'=>[
                    [
                        'action'=>'index',
                        'title'=>'客户列表'
                    ],
                    [
                        'action'=>'edit',
                        'title'=>'编辑客户',
                    ],
                    [
                        'action'=>'all',
                        'title'=>'查看所有客户',
                    ],
                    [
                        'action'=>'cert',
                        'title'=>'客户认证',
                    ],
                    [
                        'action'=>'assign',
                        'title'=>'分配客户'
                    ],
                ]
            ]
        ],
        'business'=>[
            'title'=>'销售',
            'actions'=>[
                'opportunity'=>[
                    [
                        'action'=>'index',
                        'title'=>'销售线索'
                    ],
                    [
                        'action'=>'all',
                        'title'=>'查看全部销售线索'
                    ],
                    [
                        'action'=>'assign',
                        'title'=>'分配销售线索'
                    ],
                    [
                        'action'=>'edit',
                        'title'=>'编辑销售线索',
                    ]
                ],
                'order'=>[
                    [
                        'action'=>'index',
                        'title'=>'销售订单'
                    ],
                    [
                        'action'=>'edit',
                        'title'=>'编辑销售订单',
                    ],
                    [
                        'action'=>'all',
                        'title'=>'查看全部订单',
                    ],
                    [
                        'action'=>'new_order',
                        'title'=>'建单',
                    ],
                    [
                        'action'=>'review',
                        'title'=>'审核订单',
                    ]
                ],
                'idc'=>[
                    [
                        'action'=>'index',
                        'title'=>'机房列表'
                    ]
                ],
                'ip'=>[
                    [
                        'action'=>'index',
                        'title'=>'IP池'
                    ]
                ],
                'bandwidth'=>[
                    [
                        'action'=>'index',
                        'title'=>'带宽'
                    ]
                ]
            ]
        ],
        'devops'=>[
            'title'=>'运维管理',
            'actions'=>[
                'up'=>[
                    [
                        'action'=>'index',
                        'title'=>'上架管理'
                    ]
                ],
                'wo'=>[
                    [
                        'action'=>'index',
                        'title'=>'工单管理'
                    ]
                ],
            ]
        ],
        'finance'=>[
            'title'=>'财务管理',
            'actions'=>[
                'bill'=>[
                    [
                        'action'=>'all',
                        'title'=>'账单列表'
                    ]
                ],
                'bill'=>[
                    [
                        'action'=>'confirm',
                        'title'=>'待确收'
                    ]
                ],
                'paid'=>[
                    [
                        'action'=>'index',
                        'title'=>'实收'
                    ]
                ],
            ]
        ],
        'site'=>[
            'title'=>'官网管理',
            'actions'=>[
                'site'=>[
                    [
                        'action'=>'index',
                        'title'=>'栏目管理'
                    ]
                ],
                'page'=>[
                    [
                        'action'=>'index',
                        'title'=>'栏目管理'
                    ]
                ],
                'image'=>[
                    [
                        'action'=>'index',
                        'title'=>'栏目管理'
                    ]
                ]
            ]
        ],
        'role'=>[
            'title'=>'权限管理',
            'actions'=>[
                'role'=>[
                    [
                        'action'=>'index',
                        'title'=>'角色列表'
                    ],
                    [
                        'action'=>'add',
                        'title'=>'编辑角色',
                    ]
                ]
            ]
        ]
    ]
]);
